---
# Source: netbox/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: netbox
  labels:
    helm.sh/chart: netbox-4.0.1
    app.kubernetes.io/name: netbox
    app.kubernetes.io/instance: netbox
    app.kubernetes.io/version: "v3.0.11"
    app.kubernetes.io/managed-by: Helm
---
# Source: netbox/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: netbox
  labels:
    helm.sh/chart: netbox-4.0.1
    app.kubernetes.io/name: netbox
    app.kubernetes.io/instance: netbox
    app.kubernetes.io/version: "v3.0.11"
    app.kubernetes.io/managed-by: Helm
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: netbox
    app.kubernetes.io/instance: netbox
    app.kubernetes.io/component: netbox
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30007
