name: release
on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '*'           # Push events to every tag not containing /

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_ACTION: enable
      URL: git@github.com:haminhcong/demo-ci-cd-netbox.git    
    steps:
      - name: Set RELEASE_VERSION env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          name: https://github.com/netbox-community/netbox-docker.git
          ref: refs/heads/release
  
      - name: Get Version of NetBox Docker
        run: |
          echo "::set-output name=version::$(cat VERSION)"
        shell: bash
      - id: docker-build
        name: Build the image
        run: ./build.sh ${{ env.RELEASE_VERSION }}